version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27019:27017"
    networks:
      - mynetwork
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - mynetwork
    volumes:
      - redis_data:/data

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
